CREATE TABLE USER (
  ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  USER_NAME VARCHAR(25) NOT NULL COMMENT 'User Name',
  PASSWORD VARCHAR(255) DEFAULT NULL COMMENT 'MD5 hashed password',  
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Record created time',	
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Record updated time',
  PRIMARY KEY (ID),
  UNIQUE INDEX USER_UK_1 (USER_NAME)
 )
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE USER_PROFILE (
  ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
  USER_ID BIGINT(20) UNSIGNED NOT NULL COMMENT 'User ID',
  FIRST_NAME VARCHAR(255) NOT NULL COMMENT 'First Name',
  LAST_NAME VARCHAR(255) NOT NULL COMMENT 'Last Name',
  EMAIL VARCHAR(255) DEFAULT NULL COMMENT 'Email',
  PHONE_NUMBER VARCHAR(100) DEFAULT NULL COMMENT 'Phone number',
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Record created time',	
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Record updated time',
  PRIMARY KEY (ID)
 )
ENGINE = INNODB
CHARACTER SET utf8
COLLATE utf8_general_ci;

CREATE TABLE ROLE (
	ID BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
	ROLE_NAME VARCHAR(25) NOT NULL COMMENT 'Role Name',
	DESCRIPTION VARCHAR(100) DEFAULT NULL COMMENT 'Roles Description', 
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Record created time',	
	UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Record updated time',
	PRIMARY KEY (ID),
  	UNIQUE INDEX ROLE_UK_1 (ROLE_NAME)
)
ENGINE = INNODB
CHARACTER SET UTF8
COLLATE UTF8_GENERAL_CI;

CREATE TABLE USER_ROLE (
	ID BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary key',
	USER_ID BIGINT(20) UNSIGNED NOT NULL COMMENT 'User ID',
  	ROLE_ID BIGINT(20) UNSIGNED NOT NULL COMMENT 'Role ID',
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Record created time',	
	UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Record updated time',
  	PRIMARY KEY (ID),
  	UNIQUE INDEX USER_ROLE_UK_1 (USER_ID, ROLE_ID)
)
ENGINE = INNODB
CHARACTER SET UTF8
COLLATE UTF8_GENERAL_CI;