##USER
ALTER TABLE USER_PROFILE ADD CONSTRAINT USER_USER_PROFILE_FK_1 FOREIGN KEY (USER_ID) REFERENCES USER(ID) ON DELETE RESTRICT ON UPDATE RESTRICT;

##USER_ROLE
ALTER TABLE USER_ROLE ADD CONSTRAINT USER_ROLE_FK_1 FOREIGN KEY (USER_ID) REFERENCES USER(ID) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE USER_ROLE ADD CONSTRAINT USER_ROLE_FK_2 FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID) ON DELETE RESTRICT ON UPDATE RESTRICT;
