
INSERT INTO USER ( USER_NAME, PASSWORD) VALUES ('arivuselvan', '$2a$04$sqUTsq5M.UPKV8gAFdK1Iu/YodUDlMy0kKhcA95rUPytGK47jU1M2');
INSERT INTO USER ( USER_NAME, PASSWORD) VALUES ('john', '$2a$04$sqUTsq5M.UPKV8gAFdK1Iu/YodUDlMy0kKhcA95rUPytGK47jU1M2');
INSERT INTO USER ( USER_NAME, PASSWORD) VALUES ('david','$2a$04$sqUTsq5M.UPKV8gAFdK1Iu/YodUDlMy0kKhcA95rUPytGK47jU1M2');

INSERT INTO USER_PROFILE ( USER_ID, FIRST_NAME, LAST_NAME,EMAIL, PHONE_NUMBER) VALUES ((SELECT ID FROM USER WHERE USER_NAME ='arivuselvan'),'Arivuselvan', 'Chinnasamy','arivu@gmail.com', '2456789876');
INSERT INTO USER_PROFILE ( USER_ID, FIRST_NAME, LAST_NAME,EMAIL, PHONE_NUMBER) VALUES ((SELECT ID FROM USER WHERE USER_NAME ='john'),'John', 'Doe','john@gmail.com', '23561367243');
INSERT INTO USER_PROFILE ( USER_ID, FIRST_NAME, LAST_NAME,EMAIL, PHONE_NUMBER) VALUES ((SELECT ID FROM USER WHERE USER_NAME ='david'),'David', 'Murae','davidmurae@gmail.com', '27861367243');


INSERT INTO ROLE ( ROLE_NAME, DESCRIPTION) VALUES ("Administrator", "Administrator Role");
INSERT INTO ROLE ( ROLE_NAME, DESCRIPTION) VALUES ("User", "User Role");


INSERT INTO USER_ROLE ( USER_ID, ROLE_ID) VALUES ((SELECT ID FROM USER WHERE USER_NAME = 'arivuselvan'), (SELECT ID FROM ROLE WHERE ROLE_NAME='Administrator'));
INSERT INTO USER_ROLE ( USER_ID, ROLE_ID) VALUES ((SELECT ID FROM USER WHERE USER_NAME = 'john'), (SELECT ID FROM ROLE WHERE ROLE_NAME='User'));